CREATE TABLE Productos (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Producto VARCHAR(100) NOT NULL,
    Precio_Proveedor DECIMAL(10, 4) NOT NULL,
    Unidades INT NOT NULL,
    Precio_Unidad DECIMAL(10, 4) NOT NULL,
    Precio_Publico DECIMAL(10, 4) NOT NULL,
    Fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Clientes (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(255) NOT NULL
);
CREATE TABLE Cuentas (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_Cliente INT NOT NULL,
    ID_Producto INT NOT NULL,
    Precio DECIMAL(10, 4) NOT NULL,
    Fecha DATE NOT NULL DEFAULT (CURRENT_DATE),
    Estado BOOLEAN NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES Clientes(ID) ON DELETE RESTRICT,
    FOREIGN KEY (ID_Producto) REFERENCES Productos(ID) ON DELETE RESTRICT
);
CREATE TABLE Ventas (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_Producto INT NOT NULL,
    Precio DECIMAL(10, 4) NOT NULL,
    ID_Cliente INT,
    Fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_Producto) REFERENCES Productos(ID) ON DELETE RESTRICT,
    FOREIGN KEY (ID_Cliente) REFERENCES Clientes(ID)
);