Insert Into productos(Producto,Precio_Publico) Values
('Amarantos', 5),
('Arcoiris', 12),
('Carlos V', 10),
('chicles', 12),
('Choco Zero', 18),
('Cremax', 20),
('Dulcesitos', 2),
('Duvalin', 7),
('Emperador Chicas', 12),
('Emperador Medianas', 17),
('Emperador Grandes', 19),
('Galletas de avena', 10),
('Gelatinas', 4),
('Halls', 12),
("Hershey's", 5),
('Kisses', 3),
('Kleenex', 10),
('Lunetas', 5),
('Mazapan de Chocolate', 7),
('Mentitas 2pz', 1),
('Mentos', 12),
('Nutrinut', 3.50),
('Palanqueta', 15),
('Panditas', 15),
('Pelon Grande', 18),
('Plativolos', 19),
('Paleta Chupa Chups', 12),
('Paleta Pelon', 5),
('Popotes de tamarindo', 4),
('Pollitos de Chocolate', 5),
('Pulparido Chico', 5),
('Pulparindo Grande', 10),
('Skittles', 10),
('Tartaletas', 7),
('Winnis Individual', 2),
('Winnis Chicos',3.5),
('Winnis Grandes', 5),
('Paletas Vero', 4),
('Chocolates', 22),
('Galletas Principe', 19),
('Galletas Trikitrakets', 19),
('Ricaleta', 5),
('Clorests 2pz', 2),
('Cafe de Vaso', 18),
('Cafe de taza', 12),
('Te', 12),
('Agua 600ml', 11),
('Agua 1L', 13),
('Agua 1.5L', 16),
('Lechitas', 15),
('Juguitos', 15),
('Cocas Chicas', 18),
('Agua Mineral', 19),
('Peñafiel Adas', 15),
('Jumex', 18),
('Cereal', 10),
('Sabritas', 10);



